name: deploy-book

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: self-hosted
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      # Step 2: Get the latest commit author
      - name: Get commit author
        id: commit_author
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%ae')
          echo "Commit author: $AUTHOR"
          echo "author=$AUTHOR" >> $GITHUB_ENV

      # Step 3: Check if the author matches
      - name: Check commit author
        run: |
          if [[ "$GITHUB_ENV" != "jagar2@example.com" ]]; then
            echo "This commit was not made by jagar2. Exiting."
            exit 1
          fi

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r jupyterbook/requirements.txt

      - name: Build the book
        run: |
          rm -rf ./jupyterbook/_build
          jupyter-book build ./jupyterbook

      - name: Check if SMB share is available
        run: |
          if [ ! -d "/mnt/ENGR_Courses/ENGR131_W25" ]; then
            echo "SMB share not available, exiting."
            exit 1
          fi

      # Upload artifact and copy to SMB share
      - name: Upload and Deploy
        if: contains(github.event.head_commit.message, '#build')
        run: |
          SMBSHARE="/mnt/ENGR_Courses/ENGR131_W25"
          JBPATH="./jupyterbook"
          echo "Deploying to $SMBSHARE"
          rm -rf $SMBSHARE/*
          cp -rf  $JBPATH/_build/html/* $SMBSHARE
          cp -rf ./assets/web.config $SMBSHARE